[gcp_service_account]
# ... garder votre configuration existante ici

[ghl]
api_key = "VOTRE_JETON_GHL"
base_url = "https://rest.gohighlevel.com"
timezone = "Africa/Abidjan"
history_days = 30
## Optional but recommended for some endpoints:
# location_id = "YOUR_LOCATION_ID"  # will be inferred from JWT if omitted

pipeline_ids = ["PIPELINE_ID"]
form_ids = ["FORM_ID_1", "FORM_ID_2"]  # optional; set if you want form submissions
ready_to_pay_stage_ids = ["STAGE_ID_READY"]
custom_source_field_id = ""
link_indicators = ["checkout", "pay", "stripe"]
direct_inbound_sources = ["direct", "inbound"]
page_size = 100           # taille de page API GHL
max_pages = 50            # limite de pagination pour éviter les 429
request_pause = 0.3       # pause entre pages (secondes)
max_retries = 2           # retries sur 429/5xx
retry_backoff = 1.0       # backoff exponentiel de base (s)

[ghl.stage_ids]
offers_made = ["STAGE_ID_OFFER"]

[ghl.product_ids]
first = ["PRODUCT_ID_FIRST"]
upsell = ["PRODUCT_ID_UPSELL"]
downsell = ["PRODUCT_ID_DOWNSELL"]

[ghl.user_mapping]
"USER_ID_1" = "Setter 1"
"USER_ID_2" = "Setter 2"

[ghl]
# Facultatif: liste de closers (IDs qui seront mappés via user_mapping, ou noms déjà mappés)
closers = ["USER_ID_2", "Bohdan"]
# Facultatif: sélection par défaut dans le filtre Setters
default_users = ["Bohdan"]

[ghl.source_mapping]
facebook = "From_FB"
instagram = "From_Insta"
tiktok = "From_TikTok"
linkedin = "From_LinkedIn"
forms = "From_Forms"
direct = "From_Direct"

# (Optionnel) Configuration GitHub pour charger des JSON depuis des URLs raw
[github]
# Préfixe d'URL raw commun (recommandé). Exemple:
# raw_base = "https://raw.githubusercontent.com/<user>/<repo>/<branch>/data"
raw_base = ""
# Ou URLs explicites (si définies, priment sur raw_base)
# contacts_url = ""
# opportunities_url = ""
# forms_url = ""
# messages_url = ""
# payments_url = ""
# calls_url = ""
